# Generated by Django 4.2.30 on 2026-04-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('upload', 'Uploading'), ('search', 'Searching'), ('mapping', 'Evidence Mapping'), ('tracker', 'Missing Documents'), ('ai', 'AI Processing'), ('general', 'General')], default='general', max_length=20)),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Keywords for matching user queries')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chatbot FAQ',
                'verbose_name_plural': 'Chatbot FAQs',
                'ordering': ['category', 'question'],
            },
        ),
    ]
