# Generated by Django 4.2.30 on 2026-09-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_conversation_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotfaq',
            name='category',
            field=models.CharField(choices=[('upload', 'Uploading'), ('search', 'Searching'), ('mapping', 'Evidence Mapping'), ('areas', 'Area Submissions'), ('ai', 'Document Analysis'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
