# Generated by Django 4.2.30 on 2026-05-05 07:16

from django.db import migrations, models


def migrate_viewers_to_qa_head(apps, schema_editor):
    UserProfile = apps.get_model('accounts', 'UserProfile')
    UserProfile.objects.filter(role='viewer').update(role='qa_staff')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_backfill_user_profiles'),
    ]

    operations = [
        migrations.RunPython(migrate_viewers_to_qa_head, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('qa_staff', 'QA Head')], default='qa_staff', max_length=20),
        ),
    ]
