# Generated by Django 4.2.30 on 2026-06-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_structure', '0002_seed_areas_and_categories'),
        ('accounts', '0004_userprofile_avatar_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_areas',
            field=models.ManyToManyField(blank=True, help_text='Areas this faculty member may upload to and view. Ignored for Admin / QA Head.', related_name='faculty_profiles', to='qa_structure.accreditationarea'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('qa_staff', 'QA Head'), ('faculty', 'Faculty')], default='qa_staff', max_length=20),
        ),
    ]
