# Generated by Django 4.2.30 on 2026-09-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_seed_departments"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_logout",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
