# Generated by Django 4.2.30 on 2026-04-30 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploaded_documents/%Y/%m/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('xlsx', 'XLSX'), ('jpg', 'JPG'), ('jpeg', 'JPEG'), ('png', 'PNG')], max_length=10)),
                ('department', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('document_type', models.CharField(help_text='e.g., Policy, Report, Manual, Form', max_length=100)),
                ('qa_area', models.CharField(blank=True, default='', max_length=200)),
                ('criterion', models.CharField(blank=True, default='', max_length=200)),
                ('indicator', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('ocr_text', models.TextField(blank=True, default='')),
                ('tfidf_keywords', models.JSONField(blank=True, default=list)),
                ('cluster_label', models.IntegerField(blank=True, null=True)),
                ('duplicate_status', models.CharField(choices=[('none', 'No Duplicate'), ('possible', 'Possible Duplicate'), ('confirmed_dup', 'Confirmed Duplicate')], default='none', max_length=20)),
                ('similar_documents', models.JSONField(blank=True, default=list)),
                ('recommendation', models.TextField(blank=True, default='')),
                ('evidence_status', models.CharField(choices=[('unmapped', 'Unmapped'), ('suggested', 'Suggested'), ('confirmed', 'Confirmed'), ('needs_review', 'Needs Review')], default='unmapped', max_length=20)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, default='')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ClusterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_number', models.IntegerField()),
                ('cluster_label', models.CharField(blank=True, default='', max_length=100)),
                ('top_keywords', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_results', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
