# Generated by Django 4.2.30 on 2026-05-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='True if this is an older version superseded by a newer upload.'),
        ),
    ]
