# Generated by Django 4.2.30 on 2026-05-02 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='previous_version',
            field=models.ForeignKey(blank=True, help_text='If this document replaces an older one, link it here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='documents.document'),
        ),
    ]
