# Generated by Django 4.2.30 on 2026-05-02 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_mapping', '0003_qaprogram_qarequirement_program'),
        ('documents', '0003_document_previous_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Which QA program / audit cycle this document was uploaded for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='qa_mapping.qaprogram'),
        ),
    ]
