# Generated by Django 4.2.30 on 2026-05-05 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0005_document_accreditation_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=64)),
                ('metric_value', models.FloatField()),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_status',
            field=models.CharField(choices=[('not_run', 'Not Run'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='not_run', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='duplicate_status',
            field=models.CharField(choices=[('none', 'No Duplicate'), ('pending_check', 'Pending Duplicate Check'), ('possible', 'Possible Duplicate'), ('confirmed_dup', 'Confirmed Duplicate')], default='none', max_length=20),
        ),
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('full_ai_pipeline', 'Full AI Pipeline'), ('light_post_upload', 'Light Post Upload'), ('refresh_duplicate_flags', 'Refresh Duplicate Flags'), ('reprocess_ocr', 'Reprocess OCR'), ('reindex_search_artifacts', 'Reindex Search Artifacts')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
