# Generated by Django 4.2.30 on 2026-05-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_processingmetric_document_ocr_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundjob',
            name='job_type',
            field=models.CharField(choices=[('full_ai_pipeline', 'Full AI Pipeline'), ('light_post_upload', 'Light Post Upload'), ('bulk_upload_process', 'Bulk Upload Process'), ('refresh_duplicate_flags', 'Refresh Duplicate Flags'), ('reprocess_ocr', 'Reprocess OCR'), ('reindex_search_artifacts', 'Reindex Search Artifacts')], max_length=50),
        ),
    ]
