# Generated by Django 4.2.30 on 2026-05-31 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_bulk_upload_process_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='department',
        ),
    ]
