# Generated by Django 4.2.30 on 2026-06-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_remove_document_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image_phash',
            field=models.CharField(blank=True, default='', help_text='Perceptual hash (dHash) for visual near-duplicate detection of images.', max_length=64),
        ),
    ]
