# Generated by Django 4.2.30 on 2026-09-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_document_image_phash'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_sha256',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 of the stored file. Lets exact-duplicate upload checks run as one indexed query instead of re-hashing every file on disk.', max_length=64),
        ),
    ]
