# Generated by Django 4.2.30 on 2026-09-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_backfill_content_sha256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at', '-id']},
        ),
    ]
