# Generated by Django 4.2.30 on 2026-09-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_alter_document_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='acc_category',
        ),
        migrations.RemoveField(
            model_name='document',
            name='acc_evidence_label',
        ),
        migrations.RemoveField(
            model_name='document',
            name='acc_indicator',
        ),
        migrations.RemoveField(
            model_name='document',
            name='acc_mapping_status',
        ),
        migrations.RemoveField(
            model_name='document',
            name='acc_parameter',
        ),
        migrations.RemoveField(
            model_name='document',
            name='acc_required_evidence',
        ),
    ]
