# Generated by Django 4.2.30 on 2026-09-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_remove_document_acc_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when a user deletes this document; null means not deleted. Clearing it restores the document.', null=True),
        ),
    ]
