# Generated by Django 4.2.30 on 2026-10-03 08:28

from django.conf import settings
import os

from django.db import migrations, models


def backfill_history(apps, schema_editor):
    """Give every existing document its file name and an "Uploaded" entry, dated when it was uploaded."""
    Document = apps.get_model('documents', 'Document')
    ActivityLog = apps.get_model('documents', 'ActivityLog')
    for doc in Document.objects.select_related('uploaded_by').iterator():
        name = os.path.basename(doc.file.name) if doc.file else ''
        if name and not doc.original_filename:
            Document.objects.filter(pk=doc.pk).update(original_filename=name[:255])
        if ActivityLog.objects.filter(document_id=doc.pk, action='upload_document').exists():
            continue
        uploader = doc.uploaded_by
        # Historical models carry fields, not methods, so no get_full_name() here.
        actor = (f'{uploader.first_name} {uploader.last_name}'.strip() or uploader.username) if uploader else ''
        entry = ActivityLog.objects.create(
            user=uploader, action='upload_document', document_id=doc.pk,
            document_title=(doc.title or '')[:255], actor_name=actor[:150],
            description=f'Uploaded document: {doc.title}',
        )
        if doc.uploaded_at:
            ActivityLog.objects.filter(pk=entry.pk).update(created_at=doc.uploaded_at)

import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0014_document_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="actor_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="document_title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="document",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="original_filename",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="document",
            name="purged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="DeletionBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(blank=True, default="", max_length=150)),
                (
                    "kind",
                    models.CharField(
                        choices=[("single", "Single delete"), ("bulk", "Bulk delete")],
                        default="bulk",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Undo available"),
                            ("restored", "Restored"),
                            ("finalized", "Permanently deleted"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("document_ids", models.JSONField(default=list)),
                ("document_count", models.PositiveIntegerField(default=0)),
                ("restored_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deletion_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="activitylog",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity",
                to="documents.deletionbatch",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="deletion_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="documents.deletionbatch",
            ),
        ),
        migrations.AddIndex(
            model_name="deletionbatch",
            index=models.Index(
                fields=["status", "expires_at"], name="documents_d_status_12288d_idx"
            ),
        ),
        migrations.RunPython(backfill_history, migrations.RunPython.noop),
    ]
