# Generated by Django 4.2.30 on 2026-09-27 03:59

from django.db import migrations, models
from django.db.models import Max


def backfill_read_marks(apps, schema_editor):
    """Carry each existing read time over as the last message sent by then."""
    ThreadRead = apps.get_model('messaging', 'ThreadRead')
    ThreadMessage = apps.get_model('messaging', 'ThreadMessage')
    for state in ThreadRead.objects.all().iterator():
        upto = (ThreadMessage.objects
                .filter(thread_id=state.thread_id, created_at__lte=state.last_read_at)
                .aggregate(upto=Max('id'))['upto'])
        if upto:
            ThreadRead.objects.filter(pk=state.pk).update(last_read_message_id=upto)


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadread',
            name='last_read_message_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.RunPython(backfill_read_marks, migrations.RunPython.noop),
    ]
