# Generated by Django 4.2.30 on 2026-10-03 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import messaging.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("messaging", "0003_remove_orphaned_threads"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("voice", "Voice message"),
                            ("file", "File"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255, upload_to=messaging.models._attachment_path
                    ),
                ),
                (
                    "thumbnail",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        upload_to=messaging.models._attachment_path,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MessageReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emoji", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="thread",
            name="change_seq",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="threadmessage",
            name="change_seq",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="threadmessage",
            name="client_id",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="threadmessage",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="messaging.threadmessage",
            ),
        ),
        migrations.AddField(
            model_name="threadread",
            name="typing_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="threadmessage",
            index=models.Index(
                fields=["thread", "change_seq"], name="messaging_t_thread__f8d192_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="threadmessage",
            constraint=models.UniqueConstraint(
                fields=("sender", "client_id"), name="unique_message_client_id"
            ),
        ),
        migrations.AddField(
            model_name="messagereaction",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="messaging.threadmessage",
            ),
        ),
        migrations.AddField(
            model_name="messagereaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_reactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="messageattachment",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="messaging.threadmessage",
            ),
        ),
        migrations.AddConstraint(
            model_name="messagereaction",
            constraint=models.UniqueConstraint(
                fields=("message", "user", "emoji"), name="unique_reaction"
            ),
        ),
    ]
