"""
Generate SQL that populates MySQL/MariaDB's named time zone tables.

Why this exists
---------------
Django with USE_TZ=True emits `CONVERT_TZ(col, 'UTC', 'Asia/Manila')` for any date
truncation (the dashboard's monthly charts, for example). MariaDB returns NULL for a
named zone it does not know, and Django then raises:

    ValueError: Database returned an invalid datetime value.
                Are time zone definitions for your database installed?

The usual fix is `mysql_tzinfo_to_sql /usr/share/zoneinfo`, but the Windows build
shipped with XAMPP cannot read zoneinfo files (it reports every one as "not regular
file or directory"), and Windows has no /usr/share/zoneinfo anyway.

This script builds the same SQL from dateutil's bundled IANA database (dateutil is
already a dependency via pandas), so no download and no Unix tooling is required.

Usage
-----
    python scripts/generate_mysql_timezones.py > tz.sql
    mysql -u root < tz.sql

    # only specific zones (default is settings.TIME_ZONE plus UTC):
    python scripts/generate_mysql_timezones.py Asia/Manila UTC America/New_York
    # every zone in the bundled database:
    python scripts/generate_mysql_timezones.py --all
"""
import sys

# Populated lazily by _zone_bundle().
_ZONES = None

# MariaDB stores transition times as signed 32-bit seconds since the epoch.
INT32_MIN = -(2 ** 31)
INT32_MAX = 2 ** 31 - 1


def _sql_str(value):
    return "'" + str(value).replace("\\", "\\\\").replace("'", "''") + "'"


class _FixedType:
    """Stand-in transition type for a zone with no transitions (plain UTC)."""
    offset = 0
    isdst = False
    abbr = 'UTC'


def _zone_bundle():
    """dateutil's bundled IANA database, keyed by zone name."""
    global _ZONES
    if _ZONES is None:
        from dateutil.zoneinfo import get_zonefile_instance

        _ZONES = get_zonefile_instance().zones
    return _ZONES


def _load_zone(name):
    """
    Return a parsed zone exposing dateutil's TZif internals.

    Two things that do NOT work here, both worth knowing:

    * `dateutil.tz.gettz()` on Windows returns a registry-backed `tzwin` object with
      none of the transition internals, resolved against Windows' zone list rather
      than the IANA names Django uses.
    * Parsing the `tzdata` package's files directly yields a single zero-offset type.
      Those files are TZif version 2+ whose legacy 32-bit block is deliberately
      empty, and dateutil's parser reads only that block — so Asia/Manila comes out
      as UTC, silently wrong.

    dateutil's own bundled copy is already parsed and carries the full transition
    list, so use it.
    """
    zone = _zone_bundle().get(name)
    if zone is None:
        raise LookupError(f'unknown time zone: {name}')
    return zone


def zone_rows(name, zone_id):
    """
    Return (time_zone, time_zone_name, transitions, transition_types) rows for one zone.

    Mirrors what mysql_tzinfo_to_sql emits: every distinct local-time type becomes a
    transition_type, and every UTC transition instant points at one of them.
    """
    tz = _load_zone(name)
    ttinfos = list(getattr(tz, '_ttinfo_list', None) or [])
    trans_utc = list(getattr(tz, '_trans_list_utc', None) or [])
    trans_idx = list(getattr(tz, '_trans_idx', None) or [])
    if not ttinfos:
        # A zone with no transitions at all (UTC). Emit a single fixed type so that
        # CONVERT_TZ can still resolve the name.
        std = getattr(tz, '_ttinfo_std', None)
        if std is not None:
            ttinfos = [std]
        else:
            ttinfos = [_FixedType()]

    types = []
    for idx, tti in enumerate(ttinfos):
        types.append((zone_id, idx, int(tti.offset), 1 if tti.isdst else 0, tti.abbr or 'UTC'))

    # Type 0 must be usable as the pre-first-transition default.
    transitions = []
    for when, tti in zip(trans_utc, trans_idx):
        if not (INT32_MIN <= when <= INT32_MAX):
            continue
        try:
            type_id = ttinfos.index(tti)
        except ValueError:
            continue
        transitions.append((zone_id, int(when), type_id))

    return (zone_id, 0), (name, zone_id), transitions, types


def emit(names):
    print("-- Generated by scripts/generate_mysql_timezones.py (from dateutil's bundled IANA data).")
    print('USE mysql;')
    print('TRUNCATE TABLE time_zone;')
    print('TRUNCATE TABLE time_zone_name;')
    print('TRUNCATE TABLE time_zone_transition;')
    print('TRUNCATE TABLE time_zone_transition_type;')
    print('START TRANSACTION;')

    zone_id = 0
    skipped = []
    for name in names:
        zone_id += 1
        try:
            zone, zname, transitions, types = zone_rows(name, zone_id)
        except LookupError:
            zone_id -= 1
            skipped.append(name)
            continue

        print(f'INSERT INTO time_zone (Time_zone_id, Use_leap_seconds) VALUES ({zone[0]},{_sql_str("N")});')
        print(
            'INSERT INTO time_zone_name (Name, Time_zone_id) VALUES '
            f'({_sql_str(zname[0])},{zname[1]});'
        )
        if types:
            values = ','.join(
                f'({z},{t},{off},{dst},{_sql_str(abbr)})' for z, t, off, dst, abbr in types
            )
            print(
                'INSERT INTO time_zone_transition_type '
                '(Time_zone_id, Transition_type_id, Offset, Is_DST, Abbreviation) '
                f'VALUES {values};'
            )
        # Chunk transitions so no single statement exceeds max_allowed_packet.
        for start in range(0, len(transitions), 500):
            chunk = transitions[start:start + 500]
            values = ','.join(f'({z},{w},{t})' for z, w, t in chunk)
            print(
                'INSERT INTO time_zone_transition '
                f'(Time_zone_id, Transition_time, Transition_type_id) VALUES {values};'
            )

    print('COMMIT;')
    if skipped:
        print('-- skipped unknown zones: ' + ', '.join(skipped), file=sys.stderr)


def default_names():
    """settings.TIME_ZONE plus UTC — the pair Django actually needs for CONVERT_TZ."""
    names = ['UTC']
    try:
        import os
        import django

        os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'qa_archiving_system.settings')
        django.setup()
        from django.conf import settings

        if settings.TIME_ZONE and settings.TIME_ZONE not in names:
            names.append(settings.TIME_ZONE)
    except Exception:
        names.append('Asia/Manila')
    return names


def all_names():
    """Every zone in dateutil's bundled database."""
    return sorted(_zone_bundle())


if __name__ == '__main__':
    args = [a for a in sys.argv[1:]]
    if '--all' in args:
        emit(all_names())
    elif args:
        emit(args)
    else:
        emit(default_names())
