-- Generated by scripts/generate_mysql_timezones.py (from dateutil's bundled IANA data).
USE mysql;
TRUNCATE TABLE time_zone;
TRUNCATE TABLE time_zone_name;
TRUNCATE TABLE time_zone_transition;
TRUNCATE TABLE time_zone_transition_type;
START TRANSACTION;
INSERT INTO time_zone (Time_zone_id, Use_leap_seconds) VALUES (1,'N');
INSERT INTO time_zone_name (Name, Time_zone_id) VALUES ('UTC',1);
INSERT INTO time_zone_transition_type (Time_zone_id, Transition_type_id, Offset, Is_DST, Abbreviation) VALUES (1,0,0,0,'UTC');
INSERT INTO time_zone (Time_zone_id, Use_leap_seconds) VALUES (2,'N');
INSERT INTO time_zone_name (Name, Time_zone_id) VALUES ('Asia/Manila',2);
INSERT INTO time_zone_transition_type (Time_zone_id, Transition_type_id, Offset, Is_DST, Abbreviation) VALUES (2,0,-57360,0,'LMT'),(2,1,32400,1,'PDT'),(2,2,28800,0,'PST'),(2,3,32400,0,'JST'),(2,4,28800,0,'PST');
INSERT INTO time_zone_transition (Time_zone_id, Transition_time, Transition_type_id) VALUES (2,-2147483648,2),(2,-1046678400,1),(2,-1038733200,2),(2,-873273600,3),(2,-794221200,2),(2,-496224000,1),(2,-489315600,2),(2,259344000,1),(2,275151600,2);
COMMIT;
