# Generated by Django 4.2.30 on 2026-04-30 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QARequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qa_area', models.CharField(help_text='e.g., Area I - Vision, Mission, Goals', max_length=200)),
                ('criterion', models.CharField(help_text='e.g., Criterion A', max_length=200)),
                ('indicator', models.CharField(help_text='e.g., Indicator 1', max_length=200)),
                ('required_document', models.CharField(help_text='Description of required evidence', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['qa_area', 'criterion', 'indicator'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_status', models.CharField(choices=[('suggested', 'Suggested'), ('confirmed', 'Confirmed'), ('needs_review', 'Needs Review'), ('rejected', 'Rejected')], default='suggested', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('reason', models.TextField(blank=True, default='')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_mappings', to='documents.document')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_mappings', to='qa_mapping.qarequirement')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confidence_score'],
                'unique_together': {('requirement', 'document')},
            },
        ),
    ]
