# Generated by Django 4.2.30 on 2026-05-02 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_mapping', '0002_requirementattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(help_text='Short identifier shown on badges, e.g. "ISO-IQA".', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='hsl(215, 65%, 50%)', help_text='CSS color used for badges and progress bars.', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='qarequirement',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Which QA program / audit cycle this requirement belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='qa_mapping.qaprogram'),
        ),
    ]
