# Generated by Django 4.2.30 on 2026-06-17 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_mapping', '0005_evidencemapping_accreditation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvidenceMapping',
        ),
    ]
