# Generated by Django 4.2.30 on 2026-09-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_remove_document_acc_category_and_more'),
        ('qa_structure', '0002_seed_areas_and_categories'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accreditationparameter',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='accreditationparameter',
            name='area',
        ),
        migrations.RemoveField(
            model_name='requiredevidence',
            name='indicator',
        ),
        migrations.DeleteModel(
            name='AccreditationIndicator',
        ),
        migrations.DeleteModel(
            name='AccreditationParameter',
        ),
        migrations.DeleteModel(
            name='IndicatorCategory',
        ),
        migrations.DeleteModel(
            name='RequiredEvidence',
        ),
    ]
