# Generated by Django 4.2.30 on 2026-09-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('evidence', 'Evidence Mapping'), ('duplicate', 'Duplicate Detected'), ('completion', 'Requirement Completed'), ('upload', 'Upload'), ('message', 'Direct Message'), ('system', 'System')], default='system', max_length=20),
        ),
    ]
