# Generated by Django 4.2.30 on 2026-10-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="dedupe_key",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("evidence", "Evidence Mapping"),
                    ("duplicate", "Duplicate Detected"),
                    ("completion", "Requirement Completed"),
                    ("upload", "Upload"),
                    ("deletion", "Deletion"),
                    ("message", "Direct Message"),
                    ("system", "System"),
                ],
                default="system",
                max_length=20,
            ),
        ),
    ]
